[build]
  command = "npm run build"
  publish = "dist"  # Vite uses 'dist' as output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"